-- EXIBIR O NOME TRADUZIDO E O ANO DOS FILMES CADASTRADOS EM ORDEM ALFABÉTICA
 SELECT nometraduzido, ano FROM filmes ORDER BY nometraduzido;

-- EXIBIR O NOME ARTÍSTICO DAS PESSOAS CADASTRADAS EM ORDEM ALFABÉTICA
 SELECT nomeartistico FROM pessoas ORDER BY nomeartistico;
